[package]
name = "loremaster"
version = "0.1.0"
authors = ["Sean Myers <spmyers@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
argon2 = "0.4.0"
env_logger = "0.9.0"
frontend = { path = "./frontend" }
futures = "0.3.21"
log = "0.4.16"
# perseus = { version = "0.3.2", features = ["hydrate"] }
rand = "0.8.5"
reqwasm = "0.5.0"
rocket = { version = "0.5.0-rc.1", features = [
	"secrets",
	"json",
	"tls",
	"uuid",
] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sqlx = { version = "0.5.13", features = [
	"json",
	"macros",
	"migrate",
	# "offline",
	"postgres",
	"runtime-tokio-native-tls",
	"time",
	"tls",
	"uuid",
] }
sycamore = { version = "0.7.1", features = ["ssr"] }
thiserror = "1.0.31"
time = { version = "0.2.7", features = ["serde", "std"] }
tokio = { version = "1.16.1", features = ["full"] }
tokio-stream = "0.1.8"
tokio-test = "0.4.2"
toml = "0.5.9"
ureq = "2.4.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }


[workspace]
members = ["frontend"]
