[package]
name = "loremaster"
version = "0.1.0"
authors = ["Sean Myers <spmyers@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Error handling
anyhow = "1.0.57"
# Password Encryption
argon2 = "0.4.0"
# A concurrent renderer-agnostic Virtual DOM for interactive user experiences
dioxus = { version = "0.2.4", features = ["web", "ssr"] }
# Logging
env_logger = "0.9.0"
# Provides async programming foundational functionality
futures = "0.3.21"
# Logging
log = "0.4.17"
# Random nubmer generation
rand = "0.8.5"
# Http requests library for WebAssembly
reqwasm = "0.5.0"
# Higher level HTTP client library 
reqwest = "0.11.10"
# Backend web framework
rocket = { version = "0.5.0-rc.2", features = [
	"secrets",
	"json",
	"tls",
	"uuid",
] }
# Serialization
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
# Database client/pool/toolkit
sqlx = { version = "0.5.13", features = [
	"json",
	"macros",
	"migrate",
	# "offline",
	"postgres",
	"runtime-tokio-native-tls",
	"time",
	"tls",
	"uuid",
] }
# Frontend WebAssembly library
sycamore = { version = "0.8.0-beta.6", features = ["ssr", "suspense"] }
# Error/exception handling
thiserror = "1.0.31"
# Time
time = { version = "0.2.7", features = ["serde", "std"] }
# Backend async I/O functionality
tokio = { version = "1.19.1", features = ["full"] }
tokio-stream = "0.1.8"
tokio-test = "0.4.2"
# Encode/decode TOML content/files
toml = "0.5.9"
# Implementation of Universally Unique Identifiers (Uuid)
uuid = { version = "0.8.2", features = ["v4", "serde"] }


# [workspace]
# members = ["frontend"]
