

GET http://localhost:8000/

### REGISTER
POST http://localhost:8000/authentication/register HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email_address=person@loremaster.xyz
&password=Test123!

### LOGIN
POST http://localhost:8000/authentication/authenticate HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email_address=person@loremaster.xyz
&password=Test123!

### LOGOUT
POST http://localhost:8000/authentication/logout HTTP/1.1

###
GET http://localhost:8000/chronicle/today

###
GET http://localhost:8000/chronicle/today

###
GET http://localhost:8000/chronicle/by_date

###
GET http://localhost:8000/chronicle/by_id

###
GET http://localhost:8000/chronicle/

###
GET http://localhost:8000/chronicle/server_time

###
GET http://localhost:8000/chronicle/example