[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["Sean Myers <spmyers@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
# A concurrent renderer-agnostic Virtual DOM for interactive user experiences
dioxus = { version = "0.2.4", features = ["router", "web", "ssr"] }
# Raw bindings to JS global APIs for projects using wasm-bindgen
js-sys = "0.3.57"
# Logging
log = "0.4.17"
# Http requests library for WebAssembly
reqwasm = "0.5.0"
# Higher level HTTP client library 
reqwest = { version = "0.11.10", features = ["json"] }
# Serialization/deserialization
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
# Time
time = { version = "0.2.7", features = ["serde", "std"] }
wasm-bindgen = "0.2.80"
# Implementation of Universally Unique Identifiers (Uuid) - DOES NOT COMPILE CURRENTLY
# uuid = { version = "1.1.0", features = ["v4", "serde"] }
