[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["Sean Myers <spmyers@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = { version = "0.3.60" }
log = { version = "0.4.17" }
perseus = { version = "0.3.6" }
reqwasm = { version = "0.5.0" }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = { version = "1.0.87" }
sycamore = { version = "0.7.1" }
time = { version = "0.3.16", features = ["serde", "std"] }
ureq = { version = "2.5.0" }
wasm-bindgen = { version = "0.2.83" }
web-sys = { version = "0.3.60", features = [
	"Event",
	"EventTarget",
	"HtmlDocument",
] }
