[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["Sean Myers <spmyers@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = { version = "0.3.60" }
log = { version = "0.4.17" }
perseus = { version = "0.3.6" }
reqwasm = { version = "0.5.0" }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = { version = "1.0.89" }
sycamore = { version = "0.7.1" }
time = { version = "0.3.17", features = [
	"macros",
	"serde",
	"std",
	"local-offset",
	"wasm-bindgen",
] }
ureq = { version = "2.5.0" }
uuid = { version = "1.2.2", features = ["serde"] }
wasm-bindgen = { version = "0.2.83" }
web-sys = { version = "0.3.60", features = [
	"Event",
	"EventTarget",
	"HtmlDocument",
] }
