[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["Sean Myers <spmyers@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
log = "0.4.16"
sycamore = { version = "0.7.1", features = ["ssr"] }
wasm-bindgen = "0.2.79"

[dependencies.web-sys]
features = ["HtmlInputElement", "InputEvent"]
version = "0.3.56"
