[workspace]
members = ["loremaster", "loremaster-database", "loremaster-web-server"]
default-members = ["loremaster", "loremaster-database", "loremaster-web-server"]
exclude = ["loremaster-web-interface"]
