[package]
name = "loremaster"
version = "0.1.0"
authors = ["Sean Myers <spmyers@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.23"
anyhow = "1.0.38"
toml = "0.5.8"
postgres = { version = "0.19.1", features = ["with-chrono-0_4"] }
uuid = "0.8.2"
serde = { version = "1.0", features = ["derive"] }